services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./public:/app/public
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - app
